# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 8b0170be2e4ec370eb7e86ccb65c57dca93ef296d64582a8581fe09b8b13ca4ef6e04e8df9172d88d3dcf8f259d014ec63a4db0aa502681535cd8eb0df18d6af

test:
  secret_key_base: a43654f33357d2b4720f729a0a5f94e7a2f683d67a88a5d6e805d5cd9c9544592d7b517cb8d56a7afca3528bc29949723efeb8eac741c9b41dda56e4abf6081b

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
